# Generated by Django 5.1.3 on 2024-12-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_threshold', models.FloatField()),
                ('quantity', models.FloatField()),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('pcs', 'Pieces')], max_length=10)),
                ('shortage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hananApp.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hananApp.ingredient')),
            ],
        ),
    ]
