# Generated by Django 5.1.3 on 2024-12-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hananApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='shortage',
        ),
    ]
