# Generated by Django 4.2.20 on 2025-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hananApp', '0003_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
