# Generated by Django 4.2.20 on 2025-05-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hananApp', '0004_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
